n = int(input('Digite um númeto inteiro: '))
print('A tabuada do número {} é: '.format(n))
print('='*20)
print(' 1 x {} = {} '.format(n, 1*n))
print(' 2 x {} = {} '.format(n, 2*n))
print(' 3 x {} = {} '.format(n, 3*n))
print(' 4 x {} = {} '.format(n, 4*n))
print(' 5 x {} = {} '.format(n, 5*n))
print(' 6 x {} = {} '.format(n, 6*n))
print(' 7 x {} = {} '.format(n, 7*n))
print(' 8 x {} = {} '.format(n, 8*n))
print(' 9 x {} = {} '.format(n, 9*n))
print('10 x {} = {} '.format(n, 10*n))
print('='*20)